import type { Lead } from "./types";
import { generateId } from "./store";

export const demoLeads: Lead[] = [
  {
    id: generateId(),
    businessName: "Skyline Textiles",
    ownerName: "Ahmed Raza",
    businessType: "Manufacturing",
    location: "Faisalabad",
    businessSize: "Medium",
    painPoint: "Manual inventory tracking causes frequent stockouts and overstock issues across 3 warehouses",
    email: "ahmed.raza@skyline-textiles.com",
    score: 88,
    scoreLabel: "🔥 Hot",
    status: "New",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    saved: true,
  },
  {
    id: generateId(),
    businessName: "PakCloud Solutions",
    ownerName: "Sana Tariq",
    businessType: "Tech",
    location: "Islamabad",
    businessSize: "Small",
    painPoint: "No automated client reporting system — spends 15 hours weekly on manual spreadsheets",
    email: "sana@pakcloud.io",
    score: 92,
    scoreLabel: "🔥 Hot",
    status: "New",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    saved: true,
  },
  {
    id: generateId(),
    businessName: "Al-Rashid Traders",
    ownerName: "Bilal Hassan",
    businessType: "Retail",
    location: "Karachi",
    businessSize: "Medium",
    painPoint: "Cash flow tracking is scattered across WhatsApp notes and paper ledgers",
    email: "bilal.h@alrashid.com.pk",
    score: 72,
    scoreLabel: "⚡ Warm",
    status: "Contacted",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    saved: true,
    lastContacted: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: generateId(),
    businessName: "Green Valley Hospital",
    ownerName: "Dr. Mariam Iqbal",
    businessType: "Healthcare",
    location: "Lahore",
    businessSize: "Medium",
    painPoint: "Patient billing and record management still uses legacy paper files with frequent data loss",
    email: "dr.mariam@greenvalleyhospital.pk",
    score: 68,
    scoreLabel: "⚡ Warm",
    status: "New",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    saved: true,
  },
  {
    id: generateId(),
    businessName: "Al-Madina Garments",
    ownerName: "Tariq Mehmood",
    businessType: "E-commerce",
    location: "Sialkot",
    businessSize: "Small",
    painPoint: "No unified dashboard for tracking orders across Daraz, Shopify, and Facebook Shop",
    email: "tariq@almadinagarments.com",
    score: 35,
    scoreLabel: "❄️ Cold",
    status: "New",
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    saved: true,
  },
  {
    id: generateId(),
    businessName: "Prime Logistics",
    ownerName: "Faisal Khan",
    businessType: "Logistics",
    location: "Rawalpindi",
    businessSize: "Small",
    painPoint: "Fleet expense tracking is done via messy WhatsApp groups and sticky notes",
    email: "faisal@primelogistics.pk",
    score: 28,
    scoreLabel: "❄️ Cold",
    status: "New",
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    saved: true,
  },
];
